### ISSUE TITLE
How Can I running this project

### ISSUE THREAD

**Issue by linlih** [eric135/YaNFD#1]
Could you please provide more detail about how to using this project ,Thx.

**Comment by linlih** [comment]
go run main.go works fine, Next step to send to package to the YaNFD

**Comment by eric135** [comment]
This project is very experimental at the moment, so I would recommend using a different forwarder if you want to experiment with NDN. In particular, I'd recommend NFD (https://github.com/named-data/NFD) since it's much more mature.
